server:
  port: 8123

spring:
  jpa:
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://db.lan.veltec.com.br:5432/test_paulo
    username: psousa
    password: c1p0d@t4m1